### ISSUE TITLE
Punycode.php Exception

### ISSUE THREAD

**Issue by sir-script** [algo26-matthias/idna-convert#11]
Hi Guys, 

is there any logical reason, why an exception is thrown, if the string is already a punycode string?
Punycode.php
```
 public function encode($decoded)
    {
        // We cannot encode a domain name containing the Punycode prefix
        $extract = self::byteLength(self::punycodePrefix);
        $check_pref = $this->UnicodeTranscoder->utf8_ucs4array(self::punycodePrefix);
        $check_deco = array_slice($decoded, 0, $extract);

        if ($check_pref == $check_deco) {
            throw new \InvalidArgumentException('This is already a Punycode string');
        }
```

In my opinion, it should not throw an exception. Instead, the string is valid and should be directly returned as is.
What do you think?

**Comment by mso-zlab** [comment]
Hi,

I think, this is more or less good behaviour. The task of this method is to encode a string. It cannot do it, since this is already an encoded string. 

You can easily catch this exception, although I had better used a specific exception in this case (like a StringAlreadyEncodedException).

**Comment by d00p** [comment]
In my use-case I agree with @sir-script but definetly can relate to your argument @mso-zlab.

A specific exception would be a solution but it would be sufficient to give the Exception a unique error-code so one does not need to check for the error-message (as the code is always 0).

Because there are more than this InvalidArgumentException being thrown on different errors, it is hard to distinguish the messages without string comparison.
In my case I just want to return the `$to_encode` value when it's already Punycode in my `catch()` block

**Comment by algo26-matthias** [comment]
I'm open for any improvements to the project and will also happily accept any Pull Requests.

**Comment by algo26-matthias** [comment]
Sorry to get back this late to you, I didn't receive a notification from Github about your PR.
I just accepted the proposed changes and merged it with master.

Thank you for your efforts!

**Comment by algo26-matthias** [comment]
@d00p 
I'm currently refactoring the whole library into something (hopefully) better.
Would you mind checking out the PR https://github.com/algo26-matthias/idna-convert/pull/18 and tell me, if you see the need for more specific exceptions?
Thank you very much in advance!

**Comment by d00p** [comment]
> Also the **minimum PHP version is now 7.2**

too bad, i won't be able to use this one then...
But it's nice that you are using custom exception now, at least for AlreadyPunycodeException this would make the eception code superfluous

**Comment by algo26-matthias** [comment]
@d00p 
Thank you for your feedback.
Well, PHP 7.1 is already out of active support and will receive only security fixes. 7.3 is the current stable version.
Anyway, feature-wise there's no real change from IdnaConvert 2.x to IdnaConvert 3.x (both understand the same set of IDNA), it's just better code now.

**Comment by d00p** [comment]
@algo26-matthias it's one thing what is currently stable and what is currently default on the supported distros of my software, for example debian stretch is on php-7.0 - but I'm looking forward on using 3.x in later versions as we've been using your IdnaConvert for a long time now :)
