### ISSUE TITLE
Outdated Composer package

### ISSUE THREAD

**Issue by Viliasas** [algo26-matthias/idna-convert#15]
Hello,

I've noticed that "Mso\IdnaConvert" package is outdated and it recommends using "algo26-matthias/idna-convert". If this is the case, please update Composer package to have the latest code changes, as current version is still using "Mso\IdnaConvert\IdnaConvert" namespace instead of "Algo26\IdnaConvert\IdnaConvert". All examples mention the newer namespace.

**Comment by glensc** [comment]
looks like a duplicate: https://github.com/algo26-matthias/idna-convert/issues/14#issuecomment-467365684

as I see, there's no release yet for the renamed package and the previous one works fine due as the git tag is not modified.

@algo26-matthias maybe remove the "outdated" flag until the transition is complete, so people don't come here complaining?

**Comment by Viliasas** [comment]
Examples have changed in package description: https://packagist.org/packages/algo26-matthias/idna-convert

This is somewhat misleading. I've updated the packages according to its description and only then I've noticed that it's using the old namespace.

**Comment by glensc** [comment]
I see correct namespace in your given url (https://packagist.org/packages/algo26-matthias/idna-convert):

```php
use Algo26\IdnaConvert\IdnaConvert;
```

you seeing stale cached http response from packagist.org?

**Comment by Viliasas** [comment]
If you would do "composer require algo26-matthias/idna-convert", downloaded package uses old namespace. There is a mismatch between examples and downloaded package code.

**Comment by algo26-matthias** [comment]
I can reproduce the issue, but quite don't know, what I can do on my end. The hook from GitHub over to packagist works, though.

**Comment by Viliasas** [comment]
I see that you fixed it :) The issue was that Composer was using release 1.1.0, which was made in 2016. You needed to release a new version with updated namespace.

**Comment by algo26-matthias** [comment]
Now THAT was easy :) Sorry, I was not aware of this.

**Comment by glensc** [comment]
@Viliasas your problem was that you never said what version you installed.

**Comment by Viliasas** [comment]
@glensc I assumed that it was clear that I have installed the latest that Composer had to offer :)

**Comment by glensc** [comment]
assumption is root of all evil. "current" is relative "when" you look.

i assumed you understood that new version was not released :D

**Comment by Viliasas** [comment]
Well, that was the problem. Sorry, will try to include more information in the future.
