### ISSUE TITLE
Use Travis CI for automated build testing

### ISSUE THREAD

**Issue by webignition** [algo26-matthias/idna-convert#20]
**Is your feature request related to a problem? Please describe.**
Issue #19 is trivial to catch and it looks like the tests cover it.

Having the tests run automatically when changes are pushed would prevent such matters from getting into master and releases.

**Describe the solution you'd like**
- add `require-dev` dependencies to `composer.json` to make phpunit available to the test environment (instead of depending on the host machine version, if any)
- add a `.travis.yml` build script to run the tests

**Comment by algo26-matthias** [comment]
Thanks for reporting this FR. 
I don't personally use Travis CI but I welcome any PRs for the necessary changes.

**Comment by glensc** [comment]
you still need to use your account to enable travis integration

**Comment by algo26-matthias** [comment]
@glensc Thanks for the hint, now I got, how this works :)

@webignition: Thanks again for requesting the change. Travis CI has now been integrated and setup properly.
