### ISSUE TITLE
Tilde causes exceptions

### ISSUE THREAD

**Issue by dmitryd** [algo26-matthias/idna-convert#24]
**Describe the bug**

URL like `http://example.com/~test/` cases exception `NAMEPREP: Prohibited input U+0000007E.` in file `idna-convert/src/Punycode.php` in function `namePrep` near line 335.

**To Reproduce**
1. Call `new IdnaConvert())->encode('http://example.com/~test/')`

**Expected behavior**

No exception because tilde is a valid character in URLs according to [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.3):

> 2.3.  Unreserved Characters
>
>   Characters that are allowed in a URI but do not have a reserved purpose are called unreserved.  These include uppercase and lowercase letters, decimal digits, hyphen, period, underscore, and tilde.
>
>      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
>
> URIs that differ in the replacement of an unreserved character with its corresponding percent-encoded US-ASCII octet are equivalent: they identify the same resource.  However, URI comparison implementations do not always perform normalization prior to comparison (see Section 6).  For consistency, percent-encoded octets in the ranges of ALPHA (%41-%5A and %61-%7A), DIGIT (%30-%39), hyphen (%2D), period (%2E), underscore (%5F), or **tilde (%7E)** should not be created by URI producers and, when found in a URI, should be decoded to their corresponding unreserved characters by URI normalizers.

**Solution**

`NamePrepData::$generalProhibited` should not include `126`.

**Additional link**

TYPO3 CMS is affected by this bug: https://forge.typo3.org/issues/86921

**Comment by glensc** [comment]
invalid bug report.

you're calling the wrong method. you called method to encode hostname only.

you probably want to use `convertUrl` method:
```php
new IdnaConvert())->convertUrl('http://example.com/~test/')
```

see documentation: https://github.com/algo26-matthias/idna-convert#example-4

**Comment by glensc** [comment]
altho, what could be done, is to include `~` into invalid chars to throw an exception as well:
- https://github.com/algo26-matthias/idna-convert/blob/v3.0.2/src/ToIdn.php#L44

**Comment by dmitryd** [comment]
I do not get this:

> altho, what could be done, is to include ~ into invalid chars to throw an exception as well:

Tilde is allowed in urls.

**Comment by algo26-matthias** [comment]
@dmitryd Thanks for oyur report. As @glensc already pointed out you'll have to change the call from `encode()`to `encodeUrl()`.
His second comment was pointed more or less in my direction.

Please mind, that the signature of IdnaConvert changed lately, as also pointed out in the `ReadMe.md`.

**Comment by dmitryd** [comment]
Okay, so there is no error here but the error is actually in TYPO3 CMS. I will make a corresponding note there.

Thank you.

**Comment by glensc** [comment]
https://github.com/algo26-matthias/idna-convert/issues/24#issuecomment-521307709

click on the source link I shared to get into context.
