### ISSUE TITLE
[Question] Difference between your library and php internal idn_to_ascii/idn_to_utf8

### ISSUE THREAD

**Issue by boesing** [algo26-matthias/idna-convert#28]
Hey Matthias,

I am wondering where the difference between your library and the PHP internal functions is:
- [idn_to_ascii](https://www.php.net/manual/en/function.idn-to-ascii.php)
- [idn_to_utf8](https://www.php.net/manual/en/function.idn-to-utf8.php)

Could you give some insights on why you've implemented this in PHP instead?

**Comment by algo26-matthias** [comment]
Hi Maximilian,

this library came to live back in 2003, when we were on PHP 4. There was no support for IDNA in PHP itself and even later on you had to explicitly add support through third party libraries / PECL packages. Even today you can compile PHP without intl support.
The idea of this package is to bundle it with your application and have reliable support for IDNA regardless of the target environment.

HTH,
Matthias

**Comment by boesing** [comment]
Hi Matthias,

got it. Thanks for clarification and your time. 👍
