### ISSUE TITLE
Russian domains

### ISSUE THREAD

**Issue by idem84** [algo26-matthias/idna-convert#43]
**Describe the bug**
Blank screen without errors if convert russian domains.

**To Reproduce**
utf-8 encoding
```php
$domain = '*.фтс.рф';
$idn = new ToIdn();
$domain = $idn->convert($domain);
```

**Desktop (please complete the following information):**
 - Ubuntu 22
 - PHP 8.3
 - "mso/idna-convert": "^v4.0.1"

On version 3.1.0 all work fine, as it should

**Comment by algo26-matthias** [comment]
Try using the method `$idn->convertUrl()`. `->convert()` is meant for single labels, not complete host names. Also check your error log for potential exceptions thrown.

**Comment by idem84** [comment]
> Try using the method `$idn->convertUrl()`. `->convert()` is meant for single labels, not complete host names. Also check your error log for potential exceptions thrown.
> 
> 

convertUrl don't show blank screen, but return same string *.домен.рф without changes.

Also convert function not showing any errors, error log is empty. Just blank screen.

**Comment by idem84** [comment]
> Try using the method `$idn->convertUrl()`. `->convert()` is meant for single labels, not complete host names. Also check your error log for potential exceptions thrown.
> 
> 

Also as I say, 3.1.0 version works fine.

**Comment by algo26-matthias** [comment]
A blank screen indicates, that there might be an exception somewhere, but PHP's error reporting configuration suppresses the output.
Try without the *. in front, see what happens. An * is not a valid label. Should you need to handle * as wildcard, please wrap some logic around IdnaConvert to deal with your specific use case.
